
name: Automated Testing Pipeline

on: ['push','pull_request']

jobs:

  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/checkout@v2
      with:
        python-version: 3.8

    - name: Run Tests
      run: |
        python -m unittest tests.py
